apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-develop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aoi1/argocd-repo-sample.git
    targetRevision: main
    path: manifests/develop
  destination:
    server: https://kubernetes.default.svc
    namespace: develop
  syncPolicy:
    automated: {}
